#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 20 10:32:24 2017

@author: Nicholas
"""

import pandas as pd
import csv


class entry:    # creates object for each entry
    
    def __init__(self,name, strand):
        self.name = name
        self.strand = strand

        
    def getName(self):
        return str(self.name)
    
    def getStrand(self):
        return self.strand.rstrip()
    
    

    
def f7(seq):    # in case need to remove duplicates
    seen = set()
    seen_add = seen.add
    return [x for x in seq if not (x in seen or seen_add(x))]


    

def main():
    infile = open('SE_list.csv', 'r')   # read in csv generated by SEattempt
    SE_csv= csv.reader(infile)
    next(SE_csv) # skips title
    
    col1 = []
    run = 0
    for line in infile:
        reads = line.split(',')
        field = entry(reads[1], reads[2])
        if field.getStrand()=='0':
            col1.append(field.getName())
            run+=1
        
    print(run)
    
    
    # output data to csv using pandas
    data = {'ID':col1}
    table = pd.DataFrame(data, columns = {'ID'})
    
    out = open('SE_filtered.csv', 'w')
    table.to_csv(out)
    
  
    
    
    infile.close
    
    
    
        
main()